### ISSUE TITLE
Aware of similar project GopherJS?

### ISSUE THREAD

**Issue by dmitshur** [yosbelms/cor#18]
Hi there,

I've discovered this project a few days ago when a contributor mentioned it (I think it was on reddit, might've been on hacker news). It was described as a language that focuses on the web, but is significantly inspired by simplicity and static type checking of Go. From looking at it, it looks quite cool and advanced. I like the amount of care and detail put into the documentation and getting started resources.

I wanted to ask if you were already aware of another similar project [GopherJS](https://github.com/gopherjs/gopherjs#readme). It's similar in that it also focuses on the web, but instead of creating a new language similar to/based on Go, it takes Go itself as the language. It's different in that it's not a goal to compile readable line-to-line JS output (mostly because it's really hard to do that while implementing all of Go).

Anyway, I simply wanted to ask if you're aware of that project since there are some interesting similarities in the general direction, and I have no way of knowing if you already know of it or not (I tried searching for mentions, but found none). :)

Cheers!

**Comment by yosbelms** [comment]
Hi @shurcooL thanks for look at this project and give your insight. I'm aware of GopherJS, it is certaintly an awesome project that brings Go to the browser, but there are many differences between Cor and GopherJS that you might not have noticed in the first glance.

Cor is a new language, which the syntax is inspired in Go and C#, its philosophy inspired by Go and Python. Cor aims to productivity, so, anything that looks like a stone in the way of development productivity is discarded by concept. Cor compiles to plain JavaScript which allows the resulting code run as fast as handwritten JavaScript, it is a priority due to the most connected devices are not powerful PCs, these are mobiles and tablets, to be fast and battery saver is always appreciated. In the other hand, GopherJS is just Go to JS. I really appreciate the great work of the GopherJS community, actually I'm working with Go a lot, but the GopherJS interaction whith JavaScript is verbose and not natural. Example (taken from GopherJS docs),

In GopherJS:

```
package main

import "github.com/gopherjs/gopherjs/js"

func main() {
    js.Global.Set("pet", map[string]interface{}{
        "New": New,
    })
}

type Pet struct {
    name string
}

func New(name string) *js.Object {
    return js.MakeWrapper(&Pet{name})
}

func (p *Pet) Name() string {
    return p.name
}

func (p *Pet) SetName(name string) {
    p.name = name
}
```

In Cor:

```
func init() {
    window.pet = ('New' : New)
}

func New(name) &Pet(name)

class Pet {
    name
    func Name()        me.name
    func SetName(name) me.name = name
}
```

Altenatively you can do:

```
func init() {
    window.pet = ('New' : New)
}

func New(name) {
    return &Pet(name)
}

class Pet {
    name

    func Name() {
        return me.name
    }

    func SetName(name) {
        me.name = name
    }
}
```

As you can see, Cor is a balance between succintness and readability.

**Comment by dmitshur** [comment]
Hey @yosbelms,

I'm glad you're already aware of GopherJS and seem pretty familiar with it. That's pretty much what I wanted to find out, so I'll close the issue now.

I understand the differences and you've shown good examples, thanks. Although I think we should improve that example in the GopherJS README, I don't think it's a great one. But that's a different topic. ;)

Cheers and good luck with this project! There might still be times in the future where each project can benefit from the other.
